Add option for `reuse_port` in bind
jsbronder/asyncio-dgram pull request #14
Opened 2022-07-01 08:50 UTC by yoelbassin

Hey!
I use this lib in one of my projects, and I need multiple socket instances to bind to the same (IP, port) address.

asyncio's `loop.create_datagram_endpoint` supports the argument `reuse_port` to allow the endpoint to be bound to the same port as other existing endpoints are bound to, so long as they all set this flag when being created (however, this option isn't supported on Windows and some Unixes).

I added this argument to the bind function along with tests for this feature.

Thank you for your great work!

2022-07-01 15:14 UTC, yoelbassin commented
This option is only relevant to python > 3.5, since there, the `reuse_address` argument was still valid, and if not specified it was automatically set to True on UNIX.
Since python >= 3.6.10: the `reuse_address` parameter is no longer supported due to security concerns.

2022-07-05 16:12 UTC, jsbronder commented on test/test_aio.py
> +    with pytest.raises(OSError):
I'd add a `match` here as there's a lot of potential things that could raise OSError.

`with pytest.raises(OSError, match="Address already in use")`

2022-07-05 16:14 UTC, jsbronder commented on asyncio_dgram/aio.py
> +async def bind(addr, reuse_port=None):
Please squash this commit (and the next one) into the previous commit.  I want to be sure that every commit in `master` will pass `make format lint test`.  This enables scripting git-bisect more easily.

2022-07-05 16:15 UTC, jsbronder requested changes
Please address the comments I left and the lint error from CI and I'll merge.

(Force pushing after you squash commits is perfectly fine.)

2022-07-05 20:52 UTC, merged